### ISSUE TITLE
How to get caffe model and apply into your code?

### ISSUE THREAD

**Issue by Chauncy-Cai** [tztztztztz/eql.detectron2#11]
I would like to get the result you report. But I CANNOT with the pretrained model provided by detectron2.
Can you provide the link to the cafe model(ResNet-50) you say in README?
Moreover, I am not sure whether detectron2 has code to convert caffe-model to .pth, or detectron2 can use caffe-model directly. Can you show me the code? Or the convert code written in detectron1 is OK?

**Comment by tztztztztz** [comment]
Here is the link for caffe model: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models

Detectron2 can load the caffe model directly.
