### ISSUE TITLE
Implementation Details

### ISSUE THREAD

**Issue by valencebond** [tztztztztz/eql.detectron2#4]
Thanks for your good paper and code. As in  Implementation Details Section 4.2, 

> "we make a small modiﬁcation when EQL is applied on LVIS ...... the weight term of Equation 7 will be 1 for those categories, even if they are rare ones."

In original EQL, the loss weight is 0 only for negative samples of foreground rare category . But according to Sec4.2, the weight term  for negative samples of foreground rare category will be 1, That means all samples weight is 1?

i am not familiar with LVIS datasets and the settings of additional image-level annotations, so
please correct me if there is something wrong.

**Comment by tztztztztz** [comment]
> In original EQL, the loss weight is 0 only for negative samples of foreground rare category . But according to Sec4.2, the weight term for negative samples of foreground rare category will be 1, That means all samples weight is 1? 

Yes, your understanding is right.
BTW, this implementation doesn't apply this rule since we found that it doesn't lead to a better result.
