### ISSUE TITLE
Do you have the SEQL implementation?

### ISSUE THREAD

**Issue by amirhfarzaneh** [tztztztztz/eql.detectron2#6]
Do you have the implementation for the SEQL? How can we access CIFAR-LT and ImageNet-LT?

**Comment by tztztztztz** [comment]
SEQL is designed for image classification. We do not have a plan to release it in this repo recently.

You can access CIFAR-LT at https://github.com/richardaecn/class-balanced-loss  and ImageNet-LT at https://github.com/facebookresearch/classifier-balancing
